In [18]:
import pandas as pd

from datetime import date, timedelta
import numpy as np

dates= [date.today() - timedelta(days=x) for x in range(1, 32)]
window_start = [x.strftime("%Y-%m-%d") + " 00:00:00" for x in dates]
accounts = ["c4cefa9e-8a45-45be-ae65-5a1d3972e18e", "dcf134a1-1871-49d5-8fdf-64fd82c907cf"]
account_id = [i for i in accounts for d in window_start]
size = len(account_id)
query_count =  np.random.randint(2, 50, size=size)
exec_duration = [np.random.randint(1000, 10000) * c for c in query_count]
processed_kb =[np.random.randint(100, 1000) * c for c in query_count]
credits = [exec_duration[idx] * processed_kb[idx] / 100000000 for idx,v in enumerate(query_count)]

data = {
    "account_id":  account_id,
    "sum_compute_size": np.random.randint(25555, 502234, size=size) ,
    "sum_credits_consumed":credits,
    "window_start": dates + dates,
    "account_id_window_start":[acc + "-chatbot-" + d for acc, d in zip(account_id, window_start + window_start )],
    "query_agent": ["chatbot" for i in range(size)] ,
    "query_count": query_count,
    "sum_execution_duration_ms": exec_duration,
    "sum_processed_kb": processed_kb,
    "last_query_timestamp": [d + timedelta(hours= np.random.randint(0,24)) for d in dates+dates ],
    "window_end": [d + timedelta(hours=24) for d in dates+dates ]
}
df = pd.DataFrame(data)
df.to_csv("data.csv", index=False)

In [19]:
df.head()

,account_id,sum_compute_size,sum_credits_consumed,window_start,account_id_window_start,query_agent,query_count,sum_execution_duration_ms,sum_processed_kb,last_query_timestamp,window_end
0,c4cefa9e-8a45-45be-ae65-5a1d3972e18e,393619,32.183222,2023-12-11,c4cefa9e-8a45-45be-ae65-5a1d3972e18e-chatbot-2...,chatbot,24,211176,15240,2023-12-11,2023-12-12
1,c4cefa9e-8a45-45be-ae65-5a1d3972e18e,131140,44.074008,2023-12-10,c4cefa9e-8a45-45be-ae65-5a1d3972e18e-chatbot-2...,chatbot,33,166947,26400,2023-12-10,2023-12-11
2,c4cefa9e-8a45-45be-ae65-5a1d3972e18e,92679,16.436607,2023-12-09,c4cefa9e-8a45-45be-ae65-5a1d3972e18e-chatbot-2...,chatbot,18,136494,12042,2023-12-09,2023-12-10
3,c4cefa9e-8a45-45be-ae65-5a1d3972e18e,192946,13.803919,2023-12-08,c4cefa9e-8a45-45be-ae65-5a1d3972e18e-chatbot-2...,chatbot,28,101024,13664,2023-12-08,2023-12-09
4,c4cefa9e-8a45-45be-ae65-5a1d3972e18e,232543,70.354684,2023-12-07,c4cefa9e-8a45-45be-ae65-5a1d3972e18e-chatbot-2...,chatbot,38,207328,33934,2023-12-07,2023-12-08